require: rubocop-rspec
require: rubocop-eql

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Rakefile
    - Gemfile
    - Guardfile

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FirstArrayElementLineBreak:
  Enabled: true

Style/FirstHashElementLineBreak:
  Enabled: true

Style/FirstMethodArgumentLineBreak:
  Enabled: true

Style/FirstMethodParameterLineBreak:
  Enabled: true

Style/MultilineAssignmentLayout:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/FileName:
  Enabled: false
